### ISSUE TITLE
BayesianTuner error

### ISSUE THREAD

**Issue by WENHUAN22** [cistrome/MIRA#40]
I meet some problem when executing BayesianTuner function using python 3.11 on linux system
I run the following code,
tuner = mira.topics.BayesianTuner(
    model = model,
    n_jobs=1,
    save_name = 'tutorial/0',
    #### IMPORTANT
    min_topics = 3, max_topics = 20, # tailor for your dataset!!!!
    #### See "Notes on min_topics, max_topics" above
    #storage = mira.topics.Redis() # if using REDIS backend for more (>5) processes
)

And I get the following error message,
Traceback (most recent call last):
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 53, in _create_scoped_session
    yield session
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 317, in get_study_id_from_name
    study = models.StudyModel.find_or_raise_by_name(study_name, session)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/models.py", line 69, in find_or_raise_by_name
    study = cls.find_by_name(study_name, session)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/models.py", line 62, in find_by_name
    study = session.query(cls).filter(cls.study_name == study_name).one_or_none()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1510, in one_or_none
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-43cb508175b4>", line 1, in <module>
    tuner = mira.topics.BayesianTuner(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/mira/topic_model/hyperparameter_optim/trainer.py", line 488, in __init__
    self.study = self.create_study()
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/mira/topic_model/hyperparameter_optim/trainer.py", line 495, in create_study
    return optuna.create_study(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/study/study.py", line 1138, in create_study
    study_id = storage.create_new_study(study_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_cached_storage.py", line 79, in create_new_study
    study_id = self._backend.create_new_study(study_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 236, in create_new_study
    return self.get_study_id_from_name(study_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 316, in get_study_id_from_name
    with _create_scoped_session(self.scoped_session) as session:
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/software/anaconda3/envs/mira-3.11/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 71, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 

Do you have any idea about how to fix it?

**Comment by AllenWLynch** [comment]
Hi! Did this error occur with only one job running?
